import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "@/context/UserContext";
import Navbar from "./components/navbar/Navbar";
import AuthProvider from "@/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <UserProvider>
            <Navbar />
            <div className="layout">{children}</div>
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
